language: node_js
node_js:
  - "0.11"
  - "0.10"
notifications:
  email: false
script: ./script/test
after_script: CODECLIMATE_REPO_TOKEN=094212d256c7224bdd97c0cd8e3f8de232d2512cf0184670abef7e475ca10d93 codeclimate < coverage.lcov
